networks:
  inside:
    internal: true
  outside:

services:
  # 中间件
  mysql:
    container_name: "${COMPOSE_PROJECT_NAME}_mysql" # specify container name to disable scalability
    image: mysql:8
    env_file:
      - ./env/mysql/mysql.env
    cap_add:
      - SYS_NICE  # solve the 'mbind: Operation not permitted' error
    volumes:
      - ./env/mysql/conf/:/etc/mysql/conf.d/
      - ./env/mysql/initdb/:/docker-entrypoint-initdb.d/
      - ./data/mysql/data/:/var/lib/mysql/
      - ./data/mysql/files/:/var/lib/mysql-files/
    # 如需暴露端口，取消 ports 和 outside 的注释
#    ports:
#      - "3306:3306"
    networks:
      inside:
        aliases:
          - sduoj-mysql
#      outside:
    deploy:
      restart_policy:
        condition: any
  redis:
    container_name: "${COMPOSE_PROJECT_NAME}_redis" # specify container name to disable scalability
    image: redis:alpine
    # 如需暴露端口，取消 ports 和 outside 的注释
#    ports:
#      - "6379:6379"
    networks:
      inside:
        aliases:
          - sduoj-redis
#      outside:
    deploy:
      restart_policy:
        condition: any
  rabbit:
    container_name: "${COMPOSE_PROJECT_NAME}_rabbit" # specify container name to disable scalability
    image: rabbitmq:management
    env_file:
      - ./env/rabbitmq/rabbitmq.env
    # 如需暴露端口，取消 ports 和 outside 的注释
#    ports:
#      - "5672:5672"
#      - "15672:15672"
    networks:
      inside:
        aliases:
          - sduoj-rabbit
#      outside:
    deploy:
      restart_policy:
        condition: any
  nacos:
    container_name: "${COMPOSE_PROJECT_NAME}_nacos" # specify container name to disable scalability
    build:
      context: build/sduoj-nacos/2.1.2
    env_file:
      - ./env/nacos/nacos.env
    volumes:
      - ./data/nacos/logs/:/home/nacos/logs/
    # 如需暴露端口，取消 ports 和 outside 的注释
#    ports:
#      - "${NACOS_PORT8848}:8848"
#      - "${NACOS_PORT9848}:9848"
#      - "${NACOS_PORT9849}:9849"
    networks:
      inside:
        aliases:
          - sduoj-nacos
#      outside:
    environment:
      WAIT_HOSTS: sduoj-mysql:3306
    deploy:
      restart_policy:
        condition: any
  # 前端
  frontend:
    container_name: "${COMPOSE_PROJECT_NAME}_frontend" # specify container name to disable scalability
    build:
      context: build/sduoj-frontend/latest
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    volumes:
      - ./env/frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    # 如需暴露 https，配置相应 ./env/frontend/ssl 目录下两个证书文件，并取消下面的注释
#      - ./env/frontend/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
#      - ./env/frontend/ssl/:/etc/nginx/ssl/:ro
    ports:
      - "${FRONTEND_PORT80}:80"
    # 如需暴露 https 的 443 端口，取消下面的注释
#      - "${FRONTEND_PORT443}:443"
    networks:
      inside:
        aliases:
          - sduoj-frontend
      outside:
    deploy:
      restart_policy:
        condition: any
  # 后端网关
  gateway:
    container_name: "${COMPOSE_PROJECT_NAME}_gateway" # specify container name to disable scalability
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    volumes:
      - ./data/sduoj/logs/:/root/sduoj/logs/
    environment:
      WAIT_HOSTS: sduoj-nacos:8848,sduoj-redis:6379
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: gateway
    networks:
      inside:
        aliases:
          - sduoj-gateway
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  # 后端微服务
  auth-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    volumes:
      - ./data/sduoj/logs/:/root/sduoj/logs/
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: auth
    networks:
      inside:
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  contest-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    volumes:
      - ./data/sduoj/logs/:/root/sduoj/logs/
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848,sduoj-redis:6379
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: contest
    networks:
      inside:
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  filesys-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    volumes:
      - ./data/sduoj/logs/:/root/sduoj/logs/
      - ./data/sduoj/filesys/:/root/sduoj/filesys/
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: filesys
    networks:
      inside:
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  problem-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    volumes:
      - ./data/sduoj/logs/:/root/sduoj/logs/
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848,sduoj-redis:6379,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: problem
    networks:
      inside:
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  submit-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    volumes:
      - ./data/sduoj/logs/:/root/sduoj/logs/
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848,sduoj-redis:6379,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: submit
    networks:
      inside:
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  user-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    volumes:
      - ./data/sduoj/logs/:/root/sduoj/logs/
    environment:
      WAIT_HOSTS: sduoj-mysql:3306,sduoj-nacos:8848,sduoj-redis:6379,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: user
    networks:
      inside:
      outside: # user-service needs to connect to the SMTP server
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  websocket-service:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-server
    volumes:
      - ./data/sduoj/logs/:/root/sduoj/logs/
    environment:
      WAIT_HOSTS: sduoj-nacos:8848,sduoj-redis:6379,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
      SERVICE: websocket
    networks:
      inside:
    deploy:
      resources:
        limits:
          memory: 2048M
      restart_policy:
        condition: on-failure
  # 评测机
  judger:
    image: registry.cn-beijing.aliyuncs.com/sduoj/sduoj-judger
    environment:
      WAIT_HOSTS: sduoj-nacos:8848,sduoj-rabbit:5672
      NACOS_ADDR: sduoj-nacos:8848
      ACTIVE: prod
    networks:
      inside:
    cpuset: "0"
    deploy:
      resources:
        limits:
          memory: 1536M
          pids: 1024
      restart_policy:
        condition: on-failure
